/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// int __fastcall _cxa_finalize(void *);
// void __fastcall operator delete[](void *); idb
// _DWORD __fastcall operator new[](unsigned int); idb
// void *dlopen(const char *file, int mode);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// int strcmp(const char *, const char *);
// void *dlsym(void *handle, const char *name);
// _DWORD __fastcall operator new(unsigned int); idb
int sub_B30();
int __fastcall Java_com_xunmeng_manwe_N_zlf0(int a1, int a2, int a3);
int __fastcall Java_com_xunmeng_manwe_N_zlf1(int a1, int a2, int a3, int a4, int a5, int a6, int a7);
unsigned int __fastcall sub_C48(int a1, int a2, int a3);
int __fastcall Java_com_xunmeng_manwe_N_zlf3(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf4(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf5(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf6(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf7(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
__int64 __fastcall Java_com_xunmeng_manwe_N_zlf8(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf9(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
__int64 __fastcall Java_com_xunmeng_manwe_N_zlf10(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf2(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf11(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall Java_com_xunmeng_manwe_N_zlf12(int a1, int a2, int a3);
int __fastcall Java_com_xunmeng_manwe_N_zlf13(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_1564(int a1);
int __fastcall sub_15B4(int a1);
int __fastcall sub_1604(int a1);
int __fastcall sub_1654(int a1);
int __fastcall sub_16A4(int a1);
int __fastcall sub_16F4(int a1);
int __fastcall sub_1744(int a1);
int __fastcall sub_1794(int a1);
int __fastcall sub_17E4(const char *a1);
int __fastcall sub_1870(unsigned int a1);
int __fastcall sub_1980(int a1, unsigned int a2, int a3, int a4);
int Java_com_xunmeng_manwe_N_zlf15_0();
int __fastcall sub_1B10(int a1);
int __fastcall sub_1B16(int a1, int a2);

//-------------------------------------------------------------------------
// Data declarations

char *off_3E3C[24] =
{
  "java/lang/Boolean",
  "java/lang/Byte",
  "java/lang/Character",
  "java/lang/Short",
  "java/lang/Integer",
  "java/lang/Long",
  "java/lang/Float",
  "java/lang/Double",
  "booleanValue",
  "byteValue",
  "charValue",
  "shortValue",
  "intValue",
  "longValue",
  "floatValue",
  "doubleValue",
  "()Z",
  "()B",
  "()C",
  "()S",
  "()I",
  "()J",
  "()F",
  "()D"
}; // weak
char *off_3E5C[16] =
{
  "booleanValue",
  "byteValue",
  "charValue",
  "shortValue",
  "intValue",
  "longValue",
  "floatValue",
  "doubleValue",
  "()Z",
  "()B",
  "()C",
  "()S",
  "()I",
  "()J",
  "()F",
  "()D"
}; // weak
char *off_3E7C[8] = { "()Z", "()B", "()C", "()S", "()I", "()J", "()F", "()D" }; // weak
_UNKNOWN unk_4000; // weak
_UNKNOWN unk_4004; // weak
int dword_4008; // weak
_UNKNOWN unk_400C; // weak
int dword_419C; // weak
_UNKNOWN unk_41A0; // weak


//----- (00000B30) --------------------------------------------------------
int sub_B30()
{
  return _cxa_finalize(&unk_4000);
}

//----- (00000B40) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf0(int a1, int a2, int a3)
{
  int v5; // r6
  int v6; // r5
  int result; // r0

  v5 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a3, 0);
  v6 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v5);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a3, v5);
  if ( v6 )
    result = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 108))(a1, v6);
  else
    result = 0;
  return result;
}

//----- (00000B94) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf1(int a1, int a2, int a3, int a4, int a5, int a6, int a7)
{
  int v10; // r6
  int v11; // r9
  int v12; // r4
  int v13; // r6
  void *v14; // r4

  v10 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v11 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v10);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v10);
  if ( !v11 )
    return -1;
  v12 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v13 = (*(int (__fastcall **)(int, int, const char *, int))(*(_DWORD *)a1 + 132))(a1, v11, "<init>", v12);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a5, v12);
  if ( !v13 )
    return -2;
  v14 = (void *)sub_C48(a1, a6, a7);
  (*(void (__fastcall **)(int, int, int, void *))(*(_DWORD *)a1 + 252))(a1, a3, v13, v14);
  operator delete[](v14);
  return 0;
}

//----- (00000C48) --------------------------------------------------------
unsigned int __fastcall sub_C48(int a1, int a2, int a3)
{
  int v3; // r10
  signed int v6; // r4
  __int64 v7; // r0
  unsigned int v8; // r0
  unsigned int v9; // r2
  unsigned int v10; // r3
  int v11; // r1
  unsigned int v12; // r9
  int i; // r6
  unsigned int v14; // r8
  unsigned int v15; // r11
  int v16; // r0
  int v17; // r1
  unsigned int v18; // r1
  int v20; // [sp+4h] [bp-3Ch]
  int v22; // [sp+14h] [bp-2Ch]
  unsigned int v23; // [sp+18h] [bp-28h]
  unsigned int v24; // [sp+1Ch] [bp-24h]
  unsigned int v25; // [sp+20h] [bp-20h]

  v6 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 684))(a1, a3);
  v20 = a2;
  v22 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 748))(a1, a2, 0);
  v7 = 8LL * (unsigned int)v6;
  if ( !is_mul_ok(8u, v6) )
    HIDWORD(v7) = 1;
  if ( HIDWORD(v7) )
    LODWORD(v7) = -1;
  v8 = operator new[](v7);
  v11 = *(_DWORD *)a1;
  v12 = v8;
  if ( v6 >= 1 )
  {
    for ( i = 0; i != v6; ++i )
    {
      v23 = v8;
      v24 = v10;
      v25 = v9;
      v14 = (*(int (__fastcall **)(int, int, int))(v11 + 692))(a1, a3, i);
      v15 = *(_DWORD *)(v22 + 4 * i);
      if ( v15 <= 7 )
      {
        v16 = (*(int (__fastcall **)(int, char *))(*(_DWORD *)a1 + 24))(a1, off_3E3C[v15]);
        (*(void (__fastcall **)(int, int, char *, char *))(*(_DWORD *)a1 + 132))(a1, v16, off_3E5C[v15], off_3E7C[v15]);
      }
      switch ( v15 )
      {
        case 0u:
          v8 = sub_1564(a1);
          goto LABEL_14;
        case 1u:
          v8 = sub_15B4(a1);
LABEL_14:
          v10 = v24;
          v9 = v25;
          break;
        case 2u:
          v8 = sub_1604(a1);
          v10 = v8 >> 8;
          v9 = v25;
          break;
        case 3u:
          v8 = sub_1654(a1);
          v10 = BYTE1(v8);
          v9 = v25;
          break;
        case 4u:
          v8 = sub_16A4(a1);
          goto LABEL_22;
        case 5u:
          v8 = sub_16F4(a1);
          goto LABEL_21;
        case 6u:
          v8 = sub_1744(a1);
          goto LABEL_22;
        case 7u:
          v8 = sub_1794(a1);
LABEL_21:
          v3 = v17;
LABEL_22:
          v9 = HIWORD(v8);
          v10 = BYTE1(v8);
          break;
        case 8u:
          v10 = BYTE1(v14);
          v9 = HIWORD(v14);
          v8 = v14;
          break;
        default:
          v9 = v25;
          v8 = v23;
          v10 = v24;
          break;
      }
      *(_DWORD *)(v12 + 8 * i) = (unsigned __int8)v8 | (v9 << 16) | ((unsigned __int8)v10 << 8);
      v18 = v12 + 8 * i;
      *(_DWORD *)(v18 + 4) = v3;
      v11 = *(_DWORD *)a1;
    }
  }
  (*(void (__fastcall **)(int, int, int, _DWORD))(v11 + 780))(a1, v20, v22, 0);
  return v12;
}
// C9E: variable 'v10' is possibly undefined
// CA4: variable 'v9' is possibly undefined
// D7C: variable 'v17' is possibly undefined
// D9C: variable 'v3' is possibly undefined
// 3E3C: using guessed type char *off_3E3C[24];
// 3E5C: using guessed type char *off_3E5C[16];
// 3E7C: using guessed type char *off_3E7C[8];

//----- (00000DCC) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf3(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 276))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (00000E84) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf4(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 288))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (00000F3C) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf5(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 300))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (00000FF4) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf6(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 312))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (000010AC) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf7(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 324))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (00001164) --------------------------------------------------------
__int64 __fastcall Java_com_xunmeng_manwe_N_zlf8(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  __int64 v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0LL;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0LL;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = ((__int64 (__fastcall *)(int, int, int, int, void *))*(_DWORD *)(*(_DWORD *)a1 + 336))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (00001222) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf9(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 348))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (000012E0) --------------------------------------------------------
__int64 __fastcall Java_com_xunmeng_manwe_N_zlf10(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  __int64 v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0LL;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0LL;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = ((__int64 (__fastcall *)(int, int, int, int, void *))*(_DWORD *)(*(_DWORD *)a1 + 360))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (000013B0) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf2(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6
  int v17; // r4

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 0;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 0;
  v16 = (void *)sub_C48(a1, a7, a8);
  v17 = (*(int (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 264))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return v17;
}

//----- (00001468) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf11(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v11; // r6
  int v12; // r10
  int v13; // r6
  int v14; // r0
  int v15; // r4
  void *v16; // r6

  v11 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a4, 0);
  v12 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 24))(a1, v11);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a4, v11);
  if ( !v12 )
    return 1;
  v13 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a6, 0);
  v14 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a5, 0);
  v15 = (*(int (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 132))(a1, v12, v14, v13);
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 680))(a1, a6, v13);
  if ( !v15 )
    return 2;
  v16 = (void *)sub_C48(a1, a7, a8);
  (*(void (__fastcall **)(int, int, int, int, void *))(*(_DWORD *)a1 + 372))(a1, a3, v12, v15, v16);
  operator delete[](v16);
  return 0;
}

//----- (00001522) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf12(int a1, int a2, int a3)
{
  const char *v3; // r0

  v3 = (const char *)(*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a3, 0);
  return sub_17E4(v3);
}

//----- (0000153A) --------------------------------------------------------
int __fastcall Java_com_xunmeng_manwe_N_zlf13(int a1, int a2, int a3, int a4, int a5)
{
  unsigned int v7; // r1

  v7 = (*(int (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1 + 676))(a1, a3, 0);
  return sub_1980(a1, v7, a4, a5);
}

//----- (00001564) --------------------------------------------------------
int __fastcall sub_1564(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 152))(a1);
}

//----- (000015B4) --------------------------------------------------------
int __fastcall sub_15B4(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 164))(a1);
}

//----- (00001604) --------------------------------------------------------
int __fastcall sub_1604(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 176))(a1);
}

//----- (00001654) --------------------------------------------------------
int __fastcall sub_1654(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 188))(a1);
}

//----- (000016A4) --------------------------------------------------------
int __fastcall sub_16A4(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 200))(a1);
}

//----- (000016F4) --------------------------------------------------------
int __fastcall sub_16F4(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 212))(a1);
}

//----- (00001744) --------------------------------------------------------
int __fastcall sub_1744(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 224))(a1);
}

//----- (00001794) --------------------------------------------------------
int __fastcall sub_1794(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 236))(a1);
}

//----- (000017E4) --------------------------------------------------------
int __fastcall sub_17E4(const char *a1)
{
  void *v1; // r4
  int v2; // r0
  int v4; // r2

  v1 = dlopen(a1, 0);
  if ( !v1 )
    return -1;
  pthread_mutex_lock((pthread_mutex_t *)&unk_4004);
  if ( dword_4008 < 1 )
  {
    v2 = 0;
  }
  else
  {
    v2 = 0;
    do
    {
      if ( *((void **)&unk_400C + v2) == v1 )
        break;
      ++v2;
    }
    while ( v2 < dword_4008 );
  }
  if ( v2 == dword_4008 )
  {
    v4 = dword_4008++;
    *((_DWORD *)&unk_400C + v4) = v1;
  }
  pthread_mutex_unlock((pthread_mutex_t *)&unk_4004);
  return 0;
}
// 4008: using guessed type int dword_4008;

//----- (00001870) --------------------------------------------------------
int __fastcall sub_1870(unsigned int a1)
{
  __int64 v1; // r4
  int v2; // r6
  _QWORD *v3; // r0
  int v4; // r6

  v1 = a1;
  pthread_mutex_lock((pthread_mutex_t *)&unk_4004);
  if ( dword_419C >= 1 )
  {
    do
    {
      if ( !strcmp(**((const char ***)&unk_41A0 + HIDWORD(v1)), (const char *)v1) )
        break;
      ++HIDWORD(v1);
    }
    while ( SHIDWORD(v1) < dword_419C );
  }
  if ( HIDWORD(v1) == dword_419C )
  {
    v2 = 0;
    if ( dword_4008 < 1 )
    {
LABEL_8:
      HIDWORD(v1) = 0;
    }
    else
    {
      while ( 1 )
      {
        HIDWORD(v1) = dlsym(*((void **)&unk_400C + v2), (const char *)v1);
        if ( HIDWORD(v1) )
          break;
        if ( ++v2 >= dword_4008 )
          goto LABEL_8;
      }
    }
    if ( v2 == dword_4008 )
    {
      pthread_mutex_unlock((pthread_mutex_t *)&unk_4004);
      HIDWORD(v1) = 0;
    }
    else
    {
      v3 = (_QWORD *)operator new(8u);
      *v3 = v1;
      v4 = dword_419C++;
      *((_DWORD *)&unk_41A0 + v4) = v3;
      pthread_mutex_unlock((pthread_mutex_t *)&unk_4004);
    }
  }
  else
  {
    pthread_mutex_unlock((pthread_mutex_t *)&unk_4004);
    HIDWORD(v1) = *(_DWORD *)(*((_DWORD *)&unk_41A0 + HIDWORD(v1)) + 4);
  }
  return HIDWORD(v1);
}
// 4008: using guessed type int dword_4008;
// 419C: using guessed type int dword_419C;

//----- (00001980) --------------------------------------------------------
int __fastcall sub_1980(int a1, unsigned int a2, int a3, int a4)
{
  int v7; // r0
  int (__fastcall *v8)(int, int); // r11
  signed int v9; // r6
  __int64 v10; // r0
  _DWORD *v11; // r9
  int i; // r4
  int result; // r0

  v7 = sub_1870(a2);
  if ( !v7 )
    return 0;
  v8 = (int (__fastcall *)(int, int))v7;
  v9 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 684))(a1, a4);
  v10 = 4LL * (unsigned int)v9;
  if ( !is_mul_ok(4u, v9) )
    HIDWORD(v10) = 1;
  if ( HIDWORD(v10) )
    LODWORD(v10) = -1;
  v11 = (_DWORD *)operator new[](v10);
  if ( v9 >= 1 )
  {
    for ( i = 0; i != v9; ++i )
      v11[i] = (*(int (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 692))(a1, a4, i);
  }
  switch ( v9 )
  {
    case 0:
      result = v8(a1, a3);
      break;
    case 1:
      result = ((int (__fastcall *)(int, int, _DWORD))v8)(a1, a3, *v11);
      break;
    case 2:
      result = ((int (__fastcall *)(int, int, _DWORD, _DWORD))v8)(a1, a3, *v11, v11[1]);
      break;
    case 3:
      result = ((int (__fastcall *)(int, int, _DWORD, _DWORD, _DWORD))v8)(a1, a3, *v11, v11[1], v11[2]);
      break;
    case 4:
      result = ((int (__fastcall *)(int, int, _DWORD, _DWORD, _DWORD, _DWORD))v8)(a1, a3, *v11, v11[1], v11[2], v11[3]);
      break;
    case 5:
      result = ((int (__fastcall *)(int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))v8)(
                 a1,
                 a3,
                 *v11,
                 v11[1],
                 v11[2],
                 v11[3],
                 v11[4]);
      break;
    case 6:
      result = ((int (__fastcall *)(int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))v8)(
                 a1,
                 a3,
                 *v11,
                 v11[1],
                 v11[2],
                 v11[3],
                 v11[4],
                 v11[5]);
      break;
    case 7:
      result = ((int (__fastcall *)(int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))v8)(
                 a1,
                 a3,
                 *v11,
                 v11[1],
                 v11[2],
                 v11[3],
                 v11[4],
                 v11[5],
                 v11[6]);
      break;
    default:
      return 0;
  }
  return result;
}

//----- (00001AA0) --------------------------------------------------------
int Java_com_xunmeng_manwe_N_zlf15_0()
{
  return 0;
}

//----- (00001B10) --------------------------------------------------------
int __fastcall sub_1B10(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 32))(a1);
}

//----- (00001B16) --------------------------------------------------------
int __fastcall sub_1B16(int a1, int a2)
{
  int result; // r0

  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 36))(a1, a2);
  result = 0;
  if ( !*(_DWORD *)(a2 + 4) )
    result = -6549;
  return result;
}

// nfuncs=60 queued=30 decompiled=30 lumina nreq=0 worse=0 better=0
// ALL OK, 30 function(s) have been successfully decompiled
