/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libmanwe-lib.so'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct __attribute__((aligned(4))) Elf32_Sym
{
  unsigned __int32 st_name;
  unsigned __int32 st_value;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 3 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 4 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct Elf32_Verdef
{
  unsigned __int16 vd_version;
  unsigned __int16 vd_flags;
  unsigned __int16 vd_ndx;
  unsigned __int16 vd_cnt;
  unsigned __int32 vd_hash;
  unsigned __int32 vd_aux;
  unsigned __int32 vd_next;
};

/* 6 */
struct __attribute__((aligned(4))) Elf32_Verdaux
{
  unsigned __int32 vda_name;
  unsigned __int32 vda_next;
};

/* 7 */
struct __attribute__((aligned(4))) Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file;
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 8 */
struct __attribute__((aligned(4))) Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name;
  unsigned __int32 vna_next;
};

/* 9 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 10 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 11 */
typedef __n64 int8x8_t;

/* 12 */
typedef __n64 uint8x8_t;

/* 13 */
typedef __n64 int16x4_t;

/* 14 */
typedef __n64 int32x2_t;

/* 15 */
typedef __n64 uint16x4_t;

/* 16 */
typedef __n64 uint32x2_t;

/* 17 */
typedef __n128 int8x16_t;

/* 18 */
typedef __n128 int16x8_t;

/* 19 */
typedef __n128 int32x4_t;

/* 20 */
typedef __n128 int64x2_t;

/* 21 */
typedef __n128 uint8x16_t;

/* 22 */
typedef __n128 uint16x8_t;

/* 23 */
typedef __n128 uint32x4_t;

/* 24 */
typedef __n128 uint64x2_t;

/* 25 */
typedef __n64 poly8x8_t;

/* 26 */
typedef __n64 poly16x4_t;

/* 27 */
typedef __n128 poly16x8_t;

/* 28 */
typedef __n128 poly8x16_t;

/* 29 */
typedef __n64 float32x2_t;

/* 30 */
typedef __n128 float32x4_t;

/* 31 */
typedef __n128 float64x2_t;

/* 32 */
typedef __n128 poly128_t;

